CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	CONSTRAINT UNIQ_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE CATEGORIES (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	CONSTRAINT UNIQ_NAME UNIQUE (NAME)
);

CREATE TABLE EVENTS (
	ID SERIAL PRIMARY KEY,
	ANNOTATION VARCHAR(255) NOT NULL,
	CATEGORY INTEGER,
	CONFIRMED_REQUEST INTEGER,
	CREATED TIMESTAMP,
	DESCRIPTION VARCHAR(255) NOT NULL,
	EVENT_DATE TIMESTAMP,
    LAT FLOAT,
    LON FLOAT,
	PAID BOOLEAN,
	PARTICIPANT_LIMIT INTEGER,
	PUBLISHED TIMESTAMP,
	REQUEST_MODERATION BOOLEAN,
	STATE VARCHAR(100),
	TITLE VARCHAR(255),
	VIEWS INTEGER,
    INITIATOR INTEGER,
    FOREIGN KEY (INITIATOR) REFERENCES USERS (ID),
    FOREIGN KEY (CATEGORY) REFERENCES CATEGORIES(ID)
);

CREATE TABLE REQUESTS (
	ID SERIAL PRIMARY KEY,
	CREATED TIMESTAMP,
	EVENT INTEGER,
	REQUESTER INTEGER,
	STATUS VARCHAR(255),
    FOREIGN KEY (REQUESTER) REFERENCES USERS (ID),
    FOREIGN KEY (EVENT) REFERENCES EVENTS(ID)
);

CREATE TABLE COMPILATIONS (
	ID SERIAL PRIMARY KEY,
	PINNED BOOLEAN,
	TITLE VARCHAR(255)
);

CREATE TABLE COMPILATION_EVENTS (
    compilation_id INTEGER,
    event_id INTEGER,
    PRIMARY KEY (compilation_id, event_id),
    FOREIGN KEY (compilation_id) REFERENCES COMPILATIONS (ID),
    FOREIGN KEY (event_id) REFERENCES EVENTS (ID)
);