CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	CONSTRAINT UNIQ_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE EVENTS (
	ID SERIAL PRIMARY KEY,
	ANNOTATION VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
    INITIATOR INTEGER,
    FOREIGN KEY (INITIATOR) REFERENCES USERS (id)
);